name: Build and Push Docker Images to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      IMAGE_PREFIX: ${{ secrets.DOCKER_USERNAME }}/weathernow

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/WeatherNow.Api/Dockerfile
          push: true
          tags: ${{ env.IMAGE_PREFIX }}-api:latest
      - name: Build and push Client image
        uses: docker/build-push-action@v5
        with:
          context: ./src/WeatherNow.ClientApp
          file: ./src/WeatherNow.ClientApp/Dockerfile
          push: true
          tags: ${{ env.IMAGE_PREFIX }}-client:latest