name: Weather Now CI/CD Pipeline
on: 
  workflow_dispatch:
  push:
    -branches:
      - '*'
  pull_request: 
    branches:
      - '*'

jobs:
  preBuild:
    runs-on: ubuntu-latest
    outputs: 
      buildConfig: ${{ steps.get_build_config.outputs.buildConfig }}
      branchName: ${{ steps.get_build_config.outputs.branchName }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Deteremine Build Config
        id: get_build_config
        run: | 
          if [[ -n "${GITHUB_HEAD_REF}" ]]; then 
            BRANCH="${GITHUB_HEAD_REF}"
          else 
            BRANCH="${GITHUB_HEAD_REF#refs/heads/}"
          fi
          
          if [[ "$BRANCH" == "master" ]]; then
            BUILD_CONFIG="Release"
          else 
            BUILD_CONFIG="Debug"
          fi
          
          echo "Build Config: $BUILD_CONFIG"
          echo "Branch: $BRANCH"
          
          echo "buildConfig=$BUILD_CONFIG" >> $GITHUB_OUTPUT
          echo "branchName=$BRANCH" >> $GITHUB_OUTPUT
          
  build:
    runs-on: ubuntu-latest
    needs: preBuild
    permissions: 
      contents: read
      checks: write
    steps: 
      - name: Checkout Repo 
        uses: actions/checkout@v4
      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies 
        run: dotnet restore
      - name: Build All Projects
        run: dotnet build --configuration ${{ needs.preBuild.outputs.buildConfig }}
      - name: Run Tests with Coverage
        run: |
          echo "Running tests with code coverage..."
          dotnet test --no-build --configuration ${{ needs.preBuild.outputs.buildConfig }} \
            --logger "trx;LogFileName=test_results.trx" \
            --collect:"XPlat Code Coverage" \
            --results-directory TestResults
      - name: Publish Test Results to GitHub
        uses: dorny/test-reporter@v1
        with:
          name: Unit Tests
          path: TestResults/**/*.trx
          reporter: dotnet-trx
          fail-on-error: true    
      - name: Upload Coverage Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-results
          path: TestResults/**/coverage.cobertura.xml